# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7,7)
print(random_tensor)
random_tensor.shape

tensor([[0.3720, 0.4314, 0.1350, 0.0388, 0.8640, 0.9832, 0.5125],
        [0.1644, 0.8331, 0.6739, 0.0973, 0.8929, 0.9858, 0.6238],
        [0.1956, 0.7395, 0.5905, 0.4576, 0.0802, 0.5660, 0.0080],
        [0.1259, 0.2862, 0.4226, 0.6434, 0.0930, 0.9071, 0.3437],
        [0.3967, 0.0899, 0.0371, 0.9992, 0.0775, 0.7982, 0.6402],
        [0.0763, 0.4808, 0.4843, 0.4163, 0.0653, 0.5295, 0.4804],
        [0.0423, 0.0011, 0.3246, 0.3777, 0.4058, 0.4737, 0.7174]])


torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
random_tensor_3 = torch.rand(1, 7)
print(random_tensor_3, random_tensor_3.shape)
# Perform matrix multiplication
# using @ for matrix multiplication
dot_product = random_tensor_3 @ random_tensor
print(f"\nUsing @  for matrix multiplication we have: \n{dot_product}")

# using tensor.mm for matrix multiplication
product = torch.mm(random_tensor_3, random_tensor)
print(f"\nUsing torch.mm for matrix multiplication we have: \n{product}")

tensor([[0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677]]) torch.Size([1, 7])

Using @  for matrix multiplication we have: 
tensor([[3.3895, 2.9893, 3.1231, 2.5021, 2.4269, 2.9460, 1.9052]])

Using torch.mm for matrix multiplication we have: 
tensor([[3.3895, 2.9893, 3.1231, 2.5021, 2.4269, 2.9460, 1.9052]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
import torch
Random_seed = 0

# Create two random tensors
torch.manual_seed(Random_seed)
random_tensor = torch.rand(7, 7)

torch.manual_seed(Random_seed)
random_tensor_3 = torch.rand(1, 7)

print(random_tensor)
print(random_tensor_3)

# Matrix multiply tensors
matrix_products = torch.mm(random_tensor_3, random_tensor)
matrix_products


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


tensor([[1.4453, 1.0926, 1.4581, 1.3235, 1.4729, 1.2880, 0.7752]])

In [5]:
# Set manual seed
import torch
Random_seed = 42

# Create two random tensors
torch.manual_seed(Random_seed)
random_tensor = torch.rand(7, 7)

torch.manual_seed(Random_seed)
random_tensor_3 = torch.rand(1, 7)

print(random_tensor)
print(random_tensor_3)

# Matrix multiply tensors
matrix_products = torch.mm(random_tensor_3, random_tensor)
print(f"Product is: {matrix_products}")


tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566]])
Product is: tensor([[3.0938, 2.7098, 2.7137, 2.4572, 2.0022, 2.6702, 1.5846]])


# Set manual seed
import torch
Random_seed = 0

# Create two random tensors
torch.manual_seed(Random_seed)
random_tensor = torch.rand(7, 7)

torch.manual_seed(Random_seed)
random_tensor_3 = torch.rand(1, 7)

print(random_tensor)
print(random_tensor_3)

# Matrix multiply tensors
matrix_products = torch.mm(random_tensor_3, random_tensor)
matrix_products


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

In [ ]:
# Set random seed on the GPU
RANDOM_SEED_GPU = 1234



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed


# Check for access to GPU
import torch
torch.cuda.is_available()

# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED_GPU)
tensor_A = torch.rand(2,3)
print(f"tensor_A = {tensor_A}, device = {device}")

torch.manual_seed(RANDOM_SEED_GPU)
tensor_B = torch.rand(2,3)
print(f"tensor_B = {tensor_B}, device = {device}")

tensor_A = tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]), device = cuda
tensor_B = tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]), device = cuda



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor_A_reshaped = tensor_A.reshape(3,2)
print(f"tensor_A_reshaped: \n{tensor_A_reshaped}")
Matmul_GPU = tensor_B @ tensor_A_reshaped
print(f"\n Matmul_GPU = \n{Matmul_GPU}, device = {device}, {Matmul_GPU.shape} ")

tensor_A_reshaped: 
tensor([[0.0290, 0.4019],
        [0.2598, 0.3666],
        [0.0583, 0.7006]])

 Matmul_GPU = 
tensor([[0.1204, 0.3411],
        [0.0666, 0.6596]]), device = cuda, torch.Size([2, 2]) 


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max_value = torch.max(Matmul_GPU)
print(f"maximum value is: {max_value}")

# Find min
min_value = torch.min(Matmul_GPU)
print(f"minimum value is: {min_value}")


maximum value is: 0.6596311330795288
minimum value is: 0.06662219762802124


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
max_index = torch.argmax(Matmul_GPU)
print(f"maximum index value is: {max_index}")


# Find arg min
min_index = torch.argmin(Matmul_GPU)
print(f"minimum index value is: {min_index}")

maximum index value is: 3
minimum index value is: 2



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
RANDOM_SEED = 42


# Create random tensor
torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_C_squeezed = tensor_C.squeeze()

# Print out tensors and their shapes
print(f"The shape of tensor_C is: {tensor_C.shape}")
print(f"\nThe shape of tensor_C_squeezed is: {tensor_C_squeezed.shape}")

The shape of tensor_C is: torch.Size([1, 1, 1, 10])

The shape of tensor_C_squeezed is: torch.Size([10])
