In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
!git clone https://github.com/EbubeDelight/PyTorch_projects /content/drive/MyDrive/PyTorch_project

Cloning into '/content/drive/MyDrive/PyTorch_project'...


In [ ]:
print ("Ebube is excited to learn pytorch")

Ebube is excited to learn pytorch


Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

If I have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


#Introduction to Tensors

### Creating tensors
pyTorch tensors are created using 'torch.tensor()'

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]],
                         [[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]]]])
TENSOR

tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],

         [[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]]]])

In [ ]:
TENSOR.ndim

4

In [ ]:
TENSOR.shape

torch.Size([1, 2, 3, 4])

In [ ]:
TENSOR[0]

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

### Random Tensors

Random tensors are important because neural networks start learning with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers
 https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7211, 0.6394, 0.3838, 0.6606],
        [0.7819, 0.0517, 0.6088, 0.5829],
        [0.7488, 0.9540, 0.0160, 0.0151]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, width, color channe
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###  Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size =(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones*random_tensor

tensor([[0.7211, 0.6394, 0.3838, 0.6606],
        [0.7819, 0.0517, 0.6088, 0.5829],
        [0.7488, 0.9540, 0.0160, 0.0151]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() and deprecated message, use torch.arange()
two_to_twenty = torch.arange(2,21,2)
two_to_twenty

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input =two_to_twenty)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor (eg float32 or float16)
                               device=None, # what device is your tenor on? (you can use "cuda" or "cpu" in place of None)
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, use 'tensor.device'

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0407, 0.0408, 0.0484, 0.5163],
        [0.6189, 0.6977, 0.4549, 0.9368],
        [0.8208, 0.5286, 0.6073, 0.3279]])

In [ ]:
# Find out details about some tensor
print (some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0407, 0.0408, 0.0484, 0.5163],
        [0.6189, 0.6977, 0.4549, 0.9368],
        [0.8208, 0.5286, 0.6073, 0.3279]])
Datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3 ])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subract 10
tensor-10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions

# multiplication
torch.multiply(tensor, 25) # or torch.mul

tensor([25, 50, 75])

In [ ]:
#subtract
torch.subtract(tensor, 25)

tensor([-24, -23, -22])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product )

In [ ]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
A

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
A.ndim

2

In [ ]:
A.shape

torch.Size([2, 3])

In [ ]:
B = torch.tensor([[7, 8],
                  [9, 10],
                  [11, 12]])
B

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [ ]:
B.shape

torch.Size([3, 2])

In [ ]:
# Element wise multiplication
Element_wise_mul_A_B = A*B # This will give error because size of A and B are not equal

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [ ]:
# Matrix Multiplication (dot product)
# using matmul
dot_product_A_B = torch.matmul(A, B)
dot_product_A_B

tensor([[ 58,  64],
        [139, 154]])

In [ ]:
# using @
dot_product_A_B_1 = A @ B
dot_product_A_B_1

tensor([[ 58,  64],
        [139, 154]])

### One of the most common errors in deep learning is shape error

In [ ]:
# Shapes for matrix multiplication

tensor_A = torch.tensor ([[1, 2],
                          [3, 4],
                          [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm is the same as torch.matmul (it is an alias of torch.matmul)
torch.mm(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T {tensor_B.T.shape}")
torch.mm(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T torch.Size([2, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor with minimum value win argmin()
x.argmin()

tensor(0)

In [ ]:
x[1]

tensor(10)

In [ ]:
# Find the position in tensor that has the maximum value with argmax() -> returns index position of target tensor with minimum value win argmin()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=-2)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape:{x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape:torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - add a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [ ]:
# torch.permute - rearranges dimensions of the target tensor in a specified order
x_original = torch.rand(size= (224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)
Indexing with Pytorch is similar to indexing with Numpy.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][1]

tensor([4, 5, 6])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 2, :]

tensor([[7, 8, 9]])

In [ ]:
x[0][2]

tensor([7, 8, 9])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimensions and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(x[:, 2, 2])

# Index on x to return [3, 6, 9]
print(x[:, :, 2])

tensor([9])
tensor([[3, 6, 9]])


## PyTorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.
* Data in Numpy, want in Pyt=Torch tensor -> torch.from_numpy(ndarray)
* Pytorch tensor -> Numpy -> torch.Tensor.numpy()

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Warning: when converting from numpy -> pytorch, pytorch reflets numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor+1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

### In short how a neural networl learns:

'start with random numbers -> tensor operations -> update random numbers to try and make the better representations of the data'

To reduce the randomness in neural networks and PyTorch comes the concept of a ** random seed **.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8943, 0.6060, 0.4261, 0.7139],
        [0.7286, 0.3909, 0.0478, 0.3992],
        [0.6232, 0.5184, 0.7016, 0.0754]])
tensor([[0.5254, 0.2540, 0.4242, 0.5504],
        [0.9591, 0.3228, 0.9860, 0.2133],
        [0.5919, 0.2811, 0.1921, 0.3885]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#### Extra resources for reproducibility:
https://pytorch.org/docs/stable/notes/randomness.html

### Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NIVIDIA + PyTorch working behind the scenes to make everything hunky dory (good)

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

For PyTorch since it is capable of running compute on the GPU or CPU, it is best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

Eg. run on GPU if available, else default to CPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# Count number of devices
torch.cuda.device_count()

0

### 3. Putting tensors (and models) on the GPU

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

In [ ]:
#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

array([1, 2, 3])

** N/B:**  The above code would have given me an error if I had a GPU.

In other to resolve the error, I would have done the following:
**tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()**

the does not affect the tensor on the GPU (tensor on GPU remains unchanged)

In [8]:
%cd /content/drive/MyDrive/PyTorch_project
!git add .
!git commit -m "Your commit message"
!git push

/content/drive/MyDrive/PyTorch_project
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@1741ed354c32.(none)')
error: src refspec refs/heads/main does not match any
error: failed to push some refs to 'https://github.com/EbubeDelight/PyTorch_projects'


In [16]:
!git config --global user.email "onuegbu.ebubechukwu@gmail.com"
!git config --global user.name "EbubeDelight"

In [18]:
!git config --global credential.helper store
!echo "https://<EbubeDelight>:<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>@github.com" > ~/.git-credentials